/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package ImplicitAggregation

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  test("App has a greeting") {
  }
}
