/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.scalatest.funsuite.AnyFunSuite

class SetSuite extends AnyFunSuite {

  test("An empty Set should have size 0") {
    assert(Set.empty.size == 0)
  }

//  test("Invoking head on an empty Set should produce NoSuchElementException") {
//    assertThrows[NoSuchElementException] {
//      Set.empty.head
//    }
//  }
}


//@RunWith(classOf[JUnitRunner])
//class FilesGenerationTest extends AnyFunSuite {
//
//  val SCENARIO: String = "TEST"
//  val SCENARIO_PATH: String = Utils.buildScenarioPath(SCENARIO)
//
//  test("App has a greeting") {
//    Utils.buildPath(SCENARIO)
//    (Utils.CUSTOM_CONFIGURATION_FILES ++ Utils.FIXED_CONFIGURATION_FILES).map(SCENARIO_PATH + _).foreach(println)
//    assert(true)
//  }
//}
